---
title: "README"
author: "Team2"
date: "11/6/2014"
output: html_document
---
### Introduction
One of our programming goals is to write faster R code. One way to achieve this aim is to avoid "for" loops so more time is spent on computation rather than on loops that process one element per iteration and copy data. Vectorized functions like the `apply` family were used, among other solutions, were devised to avoid `for` loops.


### Predicates
Below are a list of functions that you will need to implement for this assignment. For each function you will be given a name, the input arguments, the output type, and a description of the required behavior of the function. Your implementation of these functions may only use R’s base functionality, meaning you are not allowed to directly use any additional packages in your implementation. However, you may use other packages for testing purposes.

Be aware that there are we established algortihms to solve most of the problems listed below - don’t try to reinvent the wheel use what is known to work. Your task is translate the existing algorithms to our specific data structure and R.

The predicates task required using R's base functionality to write functions checking if input graphs were: valid, undirected, isomorphic and connected; and returns a Boolean value.

## `is_valid()`
Checks to ensure that the graph meets all requirements. A subset of these requirements were listed on the Homework 4 description, while other requirements were implied through tests in the `test_is_valid.R` file. Examples of requirements for a valid graph are:

* List of list(s)
* All primary list items are unique.
* Second list contains only edges and weights vectors of appropriate type.
* No edges to non-existent vertices.
* All weights are >0.
* Every edge has a weight.

The code for `is_valid()` is commented so it should be clear what the goal is for each `if()` statement. A step-wise process was used to develop the logic of the algorithms before they passed all of the tests.

## `is_undirected()`
Checks that all directed edges have a complimentary directed edge with the same weight in the opposite direction. A typo for a variable name within the function made it seem like this function was correctly passing all tests. Fixing the typo meant a complete rewriting of this function was needed. 

## `is_isomorphic()`


## `is_connected()`


### Method for Input/Output
### Write
Our task was to write given graphs into valid DOT files. First, we made sure that the directory existed and the file we wanted to write did not exist already and that the graph provided was a valid graph object. Some of the graphs might not have labelled vertices, but we needed proper labelling for all vertices. So, next we named all the unlabelled vertices with their indices. Labels with multiple words were also modified so that they're inside quotations to meet the DOT language specifications.
Unweighted graphs are usually written as A -> B; whereas the weighted ones are written as A -> B [weight=5];. So, we checked if the graph was weighted or not and wrote the files accordingly. Some vertices may not have any edges which are written as A;. A check was put in place to see if a vertex had no edges and was written to file accordingly.

### Read
We first checked if each line in the given file met the DOT language specification. i.e.<br>
A -> B [weight=7.2]; edges with weight<br>
A -> B; edges without weight<br>
B; vertices with no edges<br>

Then we extracted the vertices and their corresponding edges and weights from the file as lists. It is valid to exclude a vertex without edges from the file. So, we checked if there were any such vertices and added them and their corresponding blank edges and weights to the respective lists. If there was no weight associated with any edge, we gave it a weight of 1 and if any vertex had no edges, it was assigned empty edge and weight. We then converted names of edges into integer corresponding to the indices. We finally had all the vertices, edges and weights in proper types. Since a graph is a list of list of lists, we created an empty one.<br>
list(list(list(), list() ) )<br>
We then went through each unique vertex and picked its respective edges and weights and created a list of lists (list of list of edges and list of weights) corresponding to a single vertex. Then we added it back to the graph and labelled it with the vertex name.

### Method for is_isomorphic
First we check that whether the graph is valid or not, if it is not valid, then throw an error.
Second we check that the number of vertices are equal or not. If not equal, then they should not be the same. If equal, then check related edges and weights.

### Method for is_connected
First, we check that whether the graph is valid or not.
Second, we check that whether those two points exist in the graph.
Third, we find the indexed for v1 and v2.
Fourth, we construct a function to traverse through all the points in the graph. The visited vector is for recording all visited points and the queue vector is for ensuring all conncted points can be reached.
Then we traverse from v1, if it can arrive at v2, then they are connected. If not, they are not connected.

### Method for Shortest Path and Minimum Spanning Trees:

Our method for finding the shortest path and minimum spanning trees are very similar. The functions for both create a power-set of all of the possible combinations of names in the graph. It then computes all of the different permutations of each power-set and filters on the ones that match the first and last vertices given. With this, each of the paths is verified, and if it is a valid path in the graph, the weights and edges are stored. For shortest path, the path with the minimum weight is returned. For minimum spanning trees, the function goes through every combination of first and last indices, and then checks to see which of the valid paths that are returned match the number of vertices. The minimum weight is then calculated and the graph of this path is returned.

This method, however, is inefficient for graphs with a large number of vertices because the total number of paths computed is equal the sum from r=1 to n of (n!/ (n-r)!), where n is the total number of items in the list of vertices.
