---
title: "README"
author: "Team2"
date: "11/6/2014"
output: html_document
---

One of our programming goals is to write faster R code. One way to achieve this aim is to avoid "for" loops so more time is spent on computation rather than on loops that process one element per iteration and copy data. Vectorized functions like the `apply` family were used, among other solutions, were devised to avoid `for` loops.



```{r eval=FALSE}
sum(sapply(sapply(graph3, "[[", 1), length)) # Step 1
sum(sapply(sapply(graph3, "[[", 2), length)) # Step 2
sum(sapply(sapply(graph1, "[[", 1), length)) == sum(sapply(sapply(graph1, "[[", 2), length)) # Step 3
```


```{r eval=FALSE}

for (v in 1:length(graph4) ) {
  visited <- c(visited, graph4[[v]]$edges)
  if (any(graph4[[v]]$edges %in% visited)) {
    print("Found loop.")
    return(TRUE)
  }
  for (e in g[[v]]$edges) { # I have a new edge and want to traverse it.
    if (traverse(g, e, visited)) # Going to new vertex e, and keeping track of "visited"
      return(TRUE) # Found a loop. Exit if().
  }
  return(FALSE) # If I haven't found a loop above, there is no loop.
}

```