---
title: "Homework1"
author: Andrew Wong, Heather Shapiro, Jessie Li, Dipesh Gautam
output: html_document
---
Task 1: Parse the Data
```{r}
d=readLines("~cr173/Sta523/data/world_cup_goals_raw.txt")
library(stringr)

Id <- unlist(str_match_all(d," id=\"g([0-9]*)\""))[seq(2,386,2)]
PointInGoal <- unlist(str_match_all(d," pig=\"([0-9]*)\""))[seq(2,386,2)]
Class <- unlist(str_match_all(d," class=\"([a-z ]*)\""))[seq(2,386,2)]
PlayerId <- unlist(str_match_all(d," pid=\"([0-9]*)\""))[seq(2,386,2)]
MatchId <- unlist(str_match_all(d," mid=\"([0-9]*)\""))[seq(2,386,2)]
Name <- unlist(str_match_all(d, ignore.case(" pname=\"([a-z -]*[^ascii]*[a-z -&;'?]*)\"")))[seq(2,386,2)]
Team <- unlist(str_match_all(d, ignore.case(" pteam=\"([a-z &;']*)\"")))[seq(2,386,2)] 
Time <- unlist(str_match_all(d, " ptime=\"([0-9]*)\""))[seq(2,386,2)]
AddedTime <- unlist(str_match_all(d, " paddtime=\"([0-9]*)\""))[seq(2,386,2)]
GoalType <- unlist(str_match_all(d, ignore.case(" ptype=\"([a-z]*[a-z -]*)\"")))[seq(2,386,2)]
TeamImage <- unlist(str_match_all(d," pteamimg=\"([a-z /.]*)\""))[seq(2,386,2)]
PMatch <- unlist(str_match_all(d," pmatch=\"([0-9]*)\""))[seq(2,386,2)]
HorizontalLocation <- 1000-as.numeric(unlist(str_match_all(d, "left: ([0-9]*)px"))[seq(2,386,2)])
HorizontalLocation[2:193] <- unlist(str_match_all(d, "right: ([0-9]*)px"))[seq(2,384,2)]
VerticalLocationFromTop <- unlist(str_match_all(d, " top: ([0-9]*)px"))[seq(2,386,2)]

Data <- data.frame(ID = Id, PointInGoal = PointInGoal, Class = Class, PlayerId=PlayerId, MatchId=MatchId, Name= Name,Team=Team, Time=Time, AddedTime=AddedTime, GoalType=GoalType, TeamImage=TeamImage, PMatch=PMatch, HorizontalLocation=HorizontalLocation, VerticalLocationFromTop=VerticalLocationFromTop) 
```
###Task 2:Visualize the Data
```{r}
library(ggmap)
library(maptools)
library(maps)
library(plyr)


#Create new dataframe by removing "Own goal" and Class with "ispen"
DataModified <-Data[Data$GoalType!="Own goal" & grepl(".+ispen$", Class)==FALSE, ]

#Change the name for Ivory Coast and South Korea to match the geocode database
DataModified$Team=as.character(DataModified$Team)
DataModified$Team[DataModified$Team=="C&ocirc;te d'Ivoire"]= "Ivory Coast"
DataModified$Team[DataModified$Team=="Korea Republic"]= "South Korea"

#Create a new dataframe with total goals scored by players from each country
Countries <- as.data.frame(count(DataModified$Team))
colnames(Countries)= c("name","Goals")

#Get the latitude and longitude data for all 32 countries and add to the Countries data frame
Countries$name= as.character(Countries$name)
ll.Countries <- geocode(Countries$name)
Countries$lon <- ll.Countries$lon
Countries$lat <- ll.Countries$lat

# mp<-map("world", fill=TRUE, col="white", bg="grey", ylim=c(-60, 90), mar=c(0,0,0,0))
# mapWorld <-borders("world",colour="gray50",fill="white")
# mp <- ggplot() + mapWorld + geom_point(aes(x=Countries$lon,y=Countries$lat),color=c(2:33),pch=16,size=.7*Countries$Freq, alpha= I(0.6))
# mp
##+ geom_text(aes(visit.x,visit.y,label=visited$country)
```

```{r}
install.packages("rworldmap",  repos="http://cran.rstudio.com/")
install.packages("RColorBrewer",  repos="http://cran.rstudio.com/")

##+ geom_text(aes(visit.x,visit.y,label=Countries$name)
```

```{r}
# install.packages("rworldmap")
library(rworldmap)


#Plot bubble maps showing the world and separated regionwise with number of goals as size of the bubble
region<-c("world", "asia", "oceania", "africa", "europe", "latin america", "north america")

for(i in 1:7){

mapBubbles(dF=Countries, nameX="lon", nameY="lat"
,nameZSize="Goals"
,nameZColour="Goals"
,colourPalette= "rainbow"
,oceanCol="lightblue"
,landCol="white"
,main=region[i]
,addLegend=TRUE
,legendHoriz=FALSE
,addColourLegend=FALSE
,pch=16
,alpha= I(0.6)
,maxZVal=18
,catMethod="categorical"
,mapRegion=region[i])
}
# identifyCountries(getMap(),nameColumnToPlot="country")

```

